/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package huce.View;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author Admin
 */
public abstract class Form extends javax.swing.JPanel {

    /**
     * Creates new form ProductImport
     */
    public Form() {
        initComponents();
        // add event listener;
    }
    
    public static JTable createTable(String[] titles) {
        JTable jTableDetail = new JTable();
        jTableDetail.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                titles
        ));
        jTableDetail.setColumnSelectionAllowed(true);
        jTableDetail.getTableHeader().setReorderingAllowed(false);
        jTableDetail.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        return jTableDetail;
    }
    abstract public void handleEvent(Connection database);
    protected void resetForm() {
        this.jTextAccount.setText("");        
        this.jTextAmount.setText("");
        this.jTextIDForm.setText("");
        this.jTextWhere.setText("");
    }
    public void setLookUpPanel(LookUpPanel panel) {
        this.jLookUpPanel.add(panel, BorderLayout.SOUTH);
    }
    public JTextField addJTextField(JPanel parent, String text, int column) {
        parent.add(new JLabel(text));
        JTextField textField = new JTextField(column);
        textField.setBorder(new EmptyBorder(5, 5, 5, 5));
        parent.add(textField);
        return textField;
    }
    public void setTitle(String title) {
        JLabel type = new JLabel(title);
        type.setFont(new Font("Segoe UI", Font.PLAIN, 30) {
        });
        type.setForeground(Color.red);
        this.jPanelType.add(type);
    }
    // return a table with titles as the column.
   
    public void setListProductTable(JTable table) {
        this.jTableListContainer.setViewportView(table);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelType = new javax.swing.JPanel();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        jButtonDel = new javax.swing.JButton();
        jButtonCreate = new javax.swing.JButton();
        jButtonPrint = new javax.swing.JButton();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel4 = new javax.swing.JPanel();
        jPanelTop = new javax.swing.JPanel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        jTextIDForm = new javax.swing.JTextField();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        jDateCreated = new com.github.lgooddatepicker.components.DatePicker();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        jTextWhere = new javax.swing.JTextField();
        javax.swing.JPanel jPanel8 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel10 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        jTextAmount = new javax.swing.JTextField();
        jTableContainer = new javax.swing.JScrollPane();
        jPanelBottom = new javax.swing.JPanel();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        jTextAccount = new javax.swing.JTextField();
        jLookUpPanel = new javax.swing.JPanel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        jTableListContainer = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());
        add(jPanelType, java.awt.BorderLayout.PAGE_START);

        jButtonDel.setText("Xóa phiếu");
        jPanel2.add(jButtonDel);

        jButtonCreate.setText("Tạo phiếu");
        jPanel2.add(jButtonCreate);

        jButtonPrint.setText("In phiếu");
        jPanel2.add(jButtonPrint);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanelTop.setPreferredSize(new java.awt.Dimension(891, 70));
        jPanelTop.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 7));

        jLabel2.setText("Số:");
        jPanelTop.add(jLabel2);

        jTextIDForm.setColumns(5);
        jTextIDForm.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanelTop.add(jTextIDForm);

        jLabel3.setText("Ngày lập:");
        jPanelTop.add(jLabel3);
        jPanelTop.add(jDateCreated);

        jLabel4.setText("Địa điểm:");
        jPanelTop.add(jLabel4);

        jTextWhere.setColumns(10);
        jTextWhere.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanelTop.add(jTextWhere);

        jPanel4.add(jPanelTop, java.awt.BorderLayout.PAGE_START);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 0));

        jLabel8.setText("Tổng số tiền:");
        jPanel10.add(jLabel8);

        jTextAmount.setColumns(15);
        jTextAmount.setEnabled(false);
        jPanel10.add(jTextAmount);

        jPanel8.add(jPanel10, java.awt.BorderLayout.PAGE_END);
        jPanel8.add(jTableContainer, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel8, java.awt.BorderLayout.CENTER);

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5);
        flowLayout1.setAlignOnBaseline(true);
        jPanelBottom.setLayout(flowLayout1);

        jLabel7.setText("Người lập phiếu:");
        jPanelBottom.add(jLabel7);

        jTextAccount.setColumns(10);
        jTextAccount.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanelBottom.add(jTextAccount);

        jPanel4.add(jPanelBottom, java.awt.BorderLayout.PAGE_END);

        jLookUpPanel.setBackground(new java.awt.Color(204, 204, 204));
        jLookUpPanel.setLayout(new java.awt.BorderLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Danh sách sản phẩm đang có");
        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLookUpPanel.add(jLabel6, java.awt.BorderLayout.PAGE_START);
        jLabel6.getAccessibleContext().setAccessibleName("");

        jLookUpPanel.add(jTableListContainer, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jLookUpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLookUpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton jButtonCreate;
    protected javax.swing.JButton jButtonDel;
    protected javax.swing.JButton jButtonPrint;
    protected com.github.lgooddatepicker.components.DatePicker jDateCreated;
    private javax.swing.JPanel jLookUpPanel;
    protected javax.swing.JPanel jPanelBottom;
    protected javax.swing.JPanel jPanelTop;
    protected javax.swing.JPanel jPanelType;
    protected javax.swing.JScrollPane jTableContainer;
    public javax.swing.JScrollPane jTableListContainer;
    protected javax.swing.JTextField jTextAccount;
    protected javax.swing.JTextField jTextAmount;
    protected javax.swing.JTextField jTextIDForm;
    protected javax.swing.JTextField jTextWhere;
    // End of variables declaration//GEN-END:variables
}
