/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package huce.View;

import huce.Controller.HandleAddProduct;
import huce.DAO.SpotDAO;
import huce.Model.ApplyPanel;
import huce.Model.Product;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author A
 */
public class FormAddProduct extends javax.swing.JPanel {

    /**
     * Creates new form FormAddProduct
     */
    public FormAddProduct(JPanel gobackPanel) {
        initComponents();

        SpotDAO spotDAO = new SpotDAO();

        var spotNames = spotDAO.getAll().keySet();

        spotNames.forEach((id) -> {
            this.jTxtSpot.addItem(id);

        });

        this.jAddBtn.addActionListener((e) -> {
            HandleAddProduct handleAddProduct = new HandleAddProduct();
            if (handleAddProduct.add(product())) {
                ApplyPanel.apply(gobackPanel, new ListProducts(gobackPanel));
            } else {
                JOptionPane.showMessageDialog(null, "Invalid input, try again");
            }

        });
    }

    private Product product() {
        Product product = new Product();
        product.setId(this.jTxtId.getText());
        product.setName(this.jTxtName.getText());
        product.setSpotId((String) this.jTxtSpot.getSelectedItem());
        product.setFrom(this.jTxtOrigin.getText());
        product.setIssue(this.jTxtProducer.getText());
        product.setMgf(this.jDateCreated.getDateStringOrEmptyString());
        product.setExp(this.jDate.getDateStringOrEmptyString());
        product.setPriceIn(Float.parseFloat(this.jTxtIn.getText()));
        product.setPriceOut(Float.parseFloat(this.jTxtOut.getText()));
        product.setUnit(this.jTxtUnit.getText());
        return product;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel4 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        jTxtId = new javax.swing.JTextField();
        javax.swing.JLabel jText = new javax.swing.JLabel();
        jTxtName = new javax.swing.JTextField();
        jRequestNumlabel = new javax.swing.JLabel();
        jTxtSpot = new javax.swing.JComboBox<>();
        jlable1 = new javax.swing.JLabel();
        jTxtOrigin = new javax.swing.JTextField();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        jTxtProducer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jDateCreated = new com.github.lgooddatepicker.components.DatePicker();
        jLabel5 = new javax.swing.JLabel();
        jDate = new com.github.lgooddatepicker.components.DatePicker();
        jLabel6 = new javax.swing.JLabel();
        jTxtIn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTxtOut = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTxtUnit = new javax.swing.JTextField();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        jAddBtn = new javax.swing.JButton();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nhập thông tin");
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));

        jPanel4.setLayout(new java.awt.GridLayout(10, 2, 10, 10));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mã sản phẩm");
        jPanel4.add(jLabel2);
        jPanel4.add(jTxtId);

        jText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jText.setText("Tên sản phẩm ");
        jPanel4.add(jText);
        jPanel4.add(jTxtName);

        jRequestNumlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRequestNumlabel.setText("Mã vị trí ");
        jPanel4.add(jRequestNumlabel);

        jPanel4.add(jTxtSpot);

        jlable1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlable1.setText("Xuất xứ ");
        jPanel4.add(jlable1);
        jPanel4.add(jTxtOrigin);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nhà sản xuất ");
        jPanel4.add(jLabel3);
        jPanel4.add(jTxtProducer);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("NSX");
        jPanel4.add(jLabel4);
        jPanel4.add(jDateCreated);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("HSD");
        jPanel4.add(jLabel5);
        jPanel4.add(jDate);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Giá nhập ");
        jPanel4.add(jLabel6);
        jPanel4.add(jTxtIn);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Giá bán ");
        jPanel4.add(jLabel7);
        jPanel4.add(jTxtOut);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Đơn vị ");
        jPanel4.add(jLabel8);
        jPanel4.add(jTxtUnit);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jAddBtn.setText("Thêm sản phẩm");
        jPanel2.add(jAddBtn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jAddBtn;
    protected com.github.lgooddatepicker.components.DatePicker jDate;
    protected com.github.lgooddatepicker.components.DatePicker jDateCreated;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jRequestNumlabel;
    public javax.swing.JTextField jTxtId;
    private javax.swing.JTextField jTxtIn;
    public javax.swing.JTextField jTxtName;
    public javax.swing.JTextField jTxtOrigin;
    private javax.swing.JTextField jTxtOut;
    public javax.swing.JTextField jTxtProducer;
    private javax.swing.JComboBox<String> jTxtSpot;
    private javax.swing.JTextField jTxtUnit;
    private javax.swing.JLabel jlable1;
    // End of variables declaration//GEN-END:variables

}
