/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package huce.View;

import huce.DAO.ProductDAO;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class InpProductData extends javax.swing.JFrame {

    /**
     * Creates new form InpProductData
     */
    private Form form;

    public InpProductData(Form form) {
        initComponents();
        this.form = form;

        if (form instanceof FormIn) {
            this.jTextLotNumber.setEnabled(true);
            this.jRequestNumlabel.setText("Theo chứng từ");
            this.jTextRealInput.setEnabled(true);
        } else if (form instanceof FormOut) {
            this.jTextLotNumber.setEnabled(true);
            this.jTextRealInput.setEnabled(true);
            this.jlable1.setText("Thực xuất");
            this.jRequestNumlabel.setText("Theo yêu cầu");
        } else {
            this.jTextLotNumber.setEnabled(false);
            this.jRequestNumlabel.setText("Số lượng yêu cầu");
            this.jTextRealInput.setEnabled(false);
        }
        this.jOkBtn.addActionListener((var e) -> {
            try {
                var tableModel = (DefaultTableModel) form.getListProductJTable().getModel();
                var formModel = (DefaultTableModel) form.getTableDetail().getModel();
                int numRow = formModel.getRowCount() + 1;
                int selectedRow = form.getListProductJTable().getSelectedRow();
                ProductDAO pdao = new ProductDAO();
                int num
                        = Integer.parseInt((String) tableModel.getValueAt(selectedRow, 3))
                        /// minus
                        - Integer.parseInt(jTextRequestNum.getText());;
                ///
                String id = jTextID.getText();
                // nếu cái đã chọn chưa có ở trong chi tiết phiếu
                if (!isInTable(formModel, id)) {
                    // xử lý cho 2 form nhập, xuất
                    if (form instanceof FormIn || form instanceof FormOut) {
                        formModel.addRow(new String[]{"%d".formatted(numRow), id, jTextName.getText(),
                            jTextRequestNum.getText(), jTextRealInput.getText(), jTextLotNumber.getText()});
                        // riêng form
                        if (form instanceof FormOut ) {
                            // nếu xuất hàng nhiều hơn lượng có trong kho thì báo lỗi
                            if ( num < 0 ) {
                                throw new Exception();
                            }
                            // ngược lại update database.
                            pdao.exportProduct(id, Integer.parseInt(jTextRequestNum.getText()));
                            tableModel.setValueAt(num + "", selectedRow, 3);
                        }
                       
                    } 
                    // xử lý cho form yêu cầu, các loại form này không làm thay đổi dữ liệu database
                    else if (form instanceof FormRequest || form instanceof FormRequestIn) {
                        formModel.addRow(new String[]{"%d".formatted(numRow), id, jTextName.getText(),
                            jTextRequestNum.getText()});
                        
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Số lượng vượt quá hoặc bạn đã thêm sản phẩm này rồi!");
                }
                this.dispose();
            } catch (Exception evt) {
                JOptionPane.showMessageDialog(null, "Nhập sai dữ liệu");
            }
        });
    }

    private boolean isInTable(DefaultTableModel tbModel, String id) {
        int rows = tbModel.getRowCount();
        for (int i = 0; i < rows; i++) {
            if (tbModel.getValueAt(i, 1).equals(id)) {
                return true;
            }
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        jOkBtn = new javax.swing.JButton();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel4 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        jTextID = new javax.swing.JTextField();
        javax.swing.JLabel jText = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jRequestNumlabel = new javax.swing.JLabel();
        jTextRequestNum = new javax.swing.JTextField();
        jlable1 = new javax.swing.JLabel();
        jTextRealInput = new javax.swing.JTextField();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        jTextLotNumber = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nhập thông tin");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jOkBtn.setText("Ok");
        jPanel2.add(jOkBtn);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel4.setLayout(new java.awt.GridLayout(6, 2, 10, 10));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ID");
        jPanel4.add(jLabel2);

        jTextID.setEditable(false);
        jPanel4.add(jTextID);

        jText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jText.setText("Tên");
        jPanel4.add(jText);

        jTextName.setEditable(false);
        jPanel4.add(jTextName);

        jRequestNumlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRequestNumlabel.setText("Theo chứng từ");
        jPanel4.add(jRequestNumlabel);
        jPanel4.add(jTextRequestNum);

        jlable1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlable1.setText("Thực nhập");
        jPanel4.add(jlable1);
        jPanel4.add(jTextRealInput);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Đơn giá");
        jPanel4.add(jLabel3);
        jPanel4.add(jTextLotNumber);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jOkBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jRequestNumlabel;
    public javax.swing.JTextField jTextID;
    public javax.swing.JTextField jTextLotNumber;
    public javax.swing.JTextField jTextName;
    public javax.swing.JTextField jTextRealInput;
    public javax.swing.JTextField jTextRequestNum;
    private javax.swing.JLabel jlable1;
    // End of variables declaration//GEN-END:variables
}
