/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package huce.View;

import ObserverPattern.Observer;
import ObserverPattern.Subject;

/**
 *
 * @author Admin
 */
public class InpProductData extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form InpProductData
     */
    Subject form;
    public InpProductData(Subject form) {
        this.form = form;
        initComponents();
        if (form instanceof FormIn) {
            this.jTextLotNumber.setEnabled(true);
            this.jRequestNumlabel.setText("Theo chứng từ");
            this.jTextRequestNum.setEnabled(false);
            this.jTextRealInput.setEnabled(true);
        } else if (form instanceof FormOut) {
            this.jTextLotNumber.setEnabled(true);
            this.jTextRealInput.setEnabled(true);
            this.jTextRequestNum.setEnabled(false);
            this.jlable1.setText("Thực xuất");
            this.jRequestNumlabel.setText("Theo yêu cầu");
        } else {
            this.jTextLotNumber.setEnabled(false);
            this.jRequestNumlabel.setText("Số lượng yêu cầu");
            this.jTextRealInput.setEnabled(false);
        }
        this.jOkBtn.addActionListener((var e) -> {
            notifySubject();
            dispose();
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        jOkBtn = new javax.swing.JButton();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel4 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        jTextID = new javax.swing.JTextField();
        javax.swing.JLabel jText = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jRequestNumlabel = new javax.swing.JLabel();
        jTextRequestNum = new javax.swing.JTextField();
        jlable1 = new javax.swing.JLabel();
        jTextRealInput = new javax.swing.JTextField();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        jTextLotNumber = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nhập thông tin");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jOkBtn.setText("Ok");
        jPanel2.add(jOkBtn);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel4.setLayout(new java.awt.GridLayout(6, 2, 10, 10));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ID");
        jPanel4.add(jLabel2);

        jTextID.setEditable(false);
        jPanel4.add(jTextID);

        jText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jText.setText("Tên");
        jPanel4.add(jText);

        jTextName.setEditable(false);
        jPanel4.add(jTextName);

        jRequestNumlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRequestNumlabel.setText("Theo chứng từ");
        jPanel4.add(jRequestNumlabel);
        jPanel4.add(jTextRequestNum);

        jlable1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlable1.setText("Thực nhập");
        jPanel4.add(jlable1);
        jPanel4.add(jTextRealInput);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Đơn giá");
        jPanel4.add(jLabel3);
        jPanel4.add(jTextLotNumber);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jOkBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jRequestNumlabel;
    public javax.swing.JTextField jTextID;
    public javax.swing.JTextField jTextLotNumber;
    public javax.swing.JTextField jTextName;
    public javax.swing.JTextField jTextRealInput;
    public javax.swing.JTextField jTextRequestNum;
    private javax.swing.JLabel jlable1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void observe(Subject subject) {
        this.form = subject;
    }

    @Override
    public void notifySubject() {
        form.update(this);
    }
}
