/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package huce.View;

import java.awt.BorderLayout;

/**
 *
 * @author Admin
 */
public class ListProducts extends javax.swing.JPanel {

    /**
     * Creates new form ListProducts
     */
    public ListProducts() {
        initComponents();
    }
    public void setLookUpPanel(LookUpPanel panel) {
        this.jLookUpPanel.add(panel, BorderLayout.NORTH);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        jListProductsTable = new javax.swing.JTable();
        jLookUpPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jViewByType = new javax.swing.JButton();
        jOutofDateBtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Danh sách sản phẩm trong kho");
        jPanel3.add(jLabel1);

        add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jListProductsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên sản phẩm", "Nhóm hàng", "Giá tiền", "NSX", "HSD", "Số lượng tồn", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jListProductsTable);

        jPanel1.add(jScrollPane1);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jLookUpPanel.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jViewByType.setText("Sắp xếp theo nhóm hàng");
        jPanel4.add(jViewByType);

        jOutofDateBtn.setText("Xem sản phẩm hết hạn");
        jPanel4.add(jOutofDateBtn);

        jLookUpPanel.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        add(jLookUpPanel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable jListProductsTable;
    public javax.swing.JPanel jLookUpPanel;
    private javax.swing.JButton jOutofDateBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jViewByType;
    // End of variables declaration//GEN-END:variables
}
