/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package huce.View;

import huce.Controller.HandleSearchingRequestIn;
import huce.Controller.LoadListRequestIn;
import huce.Model.ApplyPanel;
import java.awt.BorderLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ListRequestsInPanel extends javax.swing.JPanel {
    public static String PENDINGMODE = "Đang chờ";
    public static String PROCESSINGMODE = "Đang xử lý";
    public static String FINISHMODE = "Hoàn thành";
    public static String CANCELMODE = "Đã hủy";
    /**
     * Creates new form ListRequestsInPanel
     */
    public ListRequestsInPanel(JPanel gobackJPanel) {
        initComponents();
        var tbModel = (DefaultTableModel)jListRequestsTable.getModel();
        // load data
        new LoadListRequestIn().loadTo(jListRequestsTable);
        //
        this.jAcceptBtn.addActionListener((e) -> {
            int row = jListRequestsTable.getSelectedRow();
            String id = (String) tbModel.getValueAt(row,1);
            ApplyPanel.apply(gobackJPanel, new FormIn(gobackJPanel, id));
        });
        this.jListRequestsTable.addMouseListener( new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int row = jListRequestsTable.getSelectedRow();
                String state = (String) tbModel.getValueAt(row, 5);                 
                jAcceptBtn.setEnabled(state.equals(PENDINGMODE) || state.equals(PROCESSINGMODE));
                jRefuseBtn.setEnabled(state.equals(PENDINGMODE));

            }
            
        } );
        this.jGobackBtn.addActionListener((e) -> {
            ApplyPanel.apply(gobackJPanel, WarehousePanel.helloPanel);
        });
        this.jBottomPanel.add(new LookUpPanel(new HandleSearchingRequestIn(), jListRequestsTable), BorderLayout.NORTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        jListRequestsTable = new javax.swing.JTable();
        jBottomPanel = new javax.swing.JPanel();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        jAcceptBtn = new javax.swing.JButton();
        jRefuseBtn = new javax.swing.JButton();
        jGobackBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jListRequestsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, "Chờ duyệt"}
            },
            new String [] {
                "STT", "ID phiếu", "ID Nhà cung cấp", "Tên nhà cung cấp", "Ngày yêu cầu", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jListRequestsTable.setShowGrid(false);
        jScrollPane1.setViewportView(jListRequestsTable);
        if (jListRequestsTable.getColumnModel().getColumnCount() > 0) {
            jListRequestsTable.getColumnModel().getColumn(0).setResizable(false);
            jListRequestsTable.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jBottomPanel.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jAcceptBtn.setText("Tạo phiếu nhập");
        jAcceptBtn.setEnabled(false);
        jPanel3.add(jAcceptBtn);

        jRefuseBtn.setText("Hủy phiếu này");
        jRefuseBtn.setEnabled(false);
        jPanel3.add(jRefuseBtn);

        jGobackBtn.setText("Quay lại");
        jPanel3.add(jGobackBtn);

        jBottomPanel.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(jBottomPanel, java.awt.BorderLayout.PAGE_END);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh sách các yêu cầu");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAcceptBtn;
    private javax.swing.JPanel jBottomPanel;
    private javax.swing.JButton jGobackBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable jListRequestsTable;
    private javax.swing.JButton jRefuseBtn;
    // End of variables declaration//GEN-END:variables
}
