/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package huce.View;

/**
 *
 * @author Admin
 */
public class ListRequestsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ListRequestsPanel
     */
    public ListRequestsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        jListRequestsTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jAcceptBtn = new javax.swing.JButton();
        jRefuseBtn = new javax.swing.JButton();
        jViewNewestRequestsBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jListRequestsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jListRequestsTable);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jAcceptBtn.setText("Duyệt");
        jAcceptBtn.setEnabled(false);
        jPanel1.add(jAcceptBtn);

        jRefuseBtn.setText("Từ chối");
        jRefuseBtn.setEnabled(false);
        jPanel1.add(jRefuseBtn);

        jViewNewestRequestsBtn.setText("Xem các yêu cầu mới");
        jPanel1.add(jViewNewestRequestsBtn);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh sách các yêu cầu");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAcceptBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable jListRequestsTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jRefuseBtn;
    private javax.swing.JButton jViewNewestRequestsBtn;
    // End of variables declaration//GEN-END:variables
}
