/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package huce.View;

import huce.Model.ApplyPanel;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class OptionImportPanel extends javax.swing.JPanel {

    /**
     * Creates new form OptionImportPanel
     */
    public OptionImportPanel(JPanel gobackJPanel) {
        initComponents();
        this.jCreateBtn.addActionListener( (e) -> {
            ApplyPanel.apply(gobackJPanel, new FormRequestIn(gobackJPanel));
        } );
        this.jViewBtn.addActionListener( (e) -> {
            ApplyPanel.apply(gobackJPanel, new ListRequestsInPanel(gobackJPanel));
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jCreateBtn = new javax.swing.JButton();
        jViewBtn = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jCreateBtn.setText("Tạo yêu cầu mới");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(jCreateBtn, gridBagConstraints);

        jViewBtn.setText("Xem yêu cầu đã tạo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(jViewBtn, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCreateBtn;
    private javax.swing.JButton jViewBtn;
    // End of variables declaration//GEN-END:variables
}
